### ISSUE TITLE
Cazzo Da..

### ISSUE THREAD

**Issue by matteobarone** [moon-php/moon#4]
Proprio adesso che volevo farmi delle API in PHP... :(

![screen shot 2018-01-16 at 18 50 18](https://user-images.githubusercontent.com/15322918/35003806-3ca14474-faee-11e7-9388-5b13f74ebfbc.png)

**Comment by damianopetrungaro** [comment]
Ahahahaha Bello de casa 😄 
Mi riprometto di rifinire il progetto di tanto in tanto ma sto troppo pieno di roba da studiare 😄 
Butta un occhio allo skeletion https://github.com/moon-php/skeleton se usi un PHPStorm vedrai che è super semplice <3
